#!/usr/bin/env python3
"""Alias map + new-service drilldown definitions to close the 86 uncovered
(cloud, service) pairs.

Every command here runs through the CUSTOMER's connection (AWS assumed-role,
Azure `az`/credentials, GCP `gcloud`/service-account, OpenAI org API key), so
the API/usage cost lands on the customer's account — never the platform.

Cost APIs per provider (customer-billed):
  AWS    -> ce:GetCostAndUsage (Cost Explorer, via assumed role)
  AZURE  -> az consumption usage list / Cost Management (customer creds)
  GCP    -> gcloud billing / BigQuery billing export + Recommender
  OpenAI -> GET /v1/organization/costs|usage (customer org key)
"""

# Tip-service label -> canonical key already present in tips-sync/drilldown_data.py maps
ALIASES = {
    'AWS': {
        'Elastic Load Balancing': 'ELB',
    },
    'AZURE': {
        'Azure Cosmos DB': 'Cosmos DB',
        'Blob Storage': 'Storage',
        'Log Analytics': 'Azure Monitor',  # resolved within GAP_MAP below
    },
    'GCP': {
        'Google Kubernetes Engine': 'GKE',
        'Pub/Sub': 'Cloud Pub/Sub',
        'Load Balancing': 'Networking',
    },
    'OpenAI': {
        'Fine-Tuning': 'Fine-tuning',
        'GPT-4': 'Model Selection',
        'GPT-4o': 'Model Selection',
        'Embeddings': 'Model Selection',
        'General': 'API Usage',
        'Prompt Optimization': 'Token Optimization',
        'Caching': 'Token Optimization',
        'Batch API': 'Token Optimization',
    },
}

# Newly authored drilldown definitions, keyed by (cloud, service).
GAP_MAP = {
  # ---------------- AWS ----------------
  ('AWS', 'API Gateway'): {"apis": ["apigateway:GetRestApis", "apigateway:GetStages(restApiId='<each>')", "cloudwatch:GetMetricStatistics(Namespace='AWS/ApiGateway',MetricName='Count',Period=2592000,Statistics=['Sum'])", "ce:GetCostAndUsage(Filter={SERVICE:['Amazon API Gateway']},GroupBy=USAGE_TYPE)"], "drilldownInstructions": "List APIs and stages. Disable caching on low-traffic stages ($0.02/hr/GB). Switch REST APIs to cheaper HTTP APIs where features allow (up to 70% cheaper). Find zero-traffic APIs."},
  ('AWS', 'Amplify'): {"apis": ["amplify:ListApps", "amplify:ListBranches(appId='<each>')", "ce:GetCostAndUsage(Filter={SERVICE:['AWS Amplify']},GroupBy=USAGE_TYPE)"], "drilldownInstructions": "List apps and branches. Delete apps with no deployment in >90 days. Break cost into build minutes vs hosting/data-transfer; reduce build frequency."},
  ('AWS', 'AppSync'): {"apis": ["appsync:ListGraphqlApis", "appsync:ListResolvers(apiId='<each>')", "cloudwatch:GetMetricStatistics(Namespace='AWS/AppSync',MetricName='4XXError')", "ce:GetCostAndUsage(Filter={SERVICE:['AWS AppSync']},GroupBy=USAGE_TYPE)"], "drilldownInstructions": "List GraphQL APIs. Cost is per query/data-modification + real-time updates. Find idle APIs, enable caching for hot queries, and prune unused data sources."},
  ('AWS', 'Athena'): {"apis": ["athena:ListWorkGroups", "athena:GetWorkGroup(WorkGroup='<each>')", "ce:GetCostAndUsage(Filter={SERVICE:['Amazon Athena']},GroupBy=USAGE_TYPE)"], "drilldownInstructions": "Athena is $5/TB scanned. Enforce per-query data-scanned limits per workgroup, convert data to Parquet + partition it, and check result-reuse to cut scanned bytes."},
  ('AWS', 'CloudWatch'): {"apis": ["cloudwatch:ListMetrics", "cloudwatch:DescribeAlarms", "logs:DescribeLogGroups", "ce:GetCostAndUsage(Filter={SERVICE:['AmazonCloudWatch']},GroupBy=USAGE_TYPE)"], "drilldownInstructions": "Break cost into custom metrics ($0.30 each), dashboards, alarms, and logs. Delete unused custom metrics/alarms; reduce high-resolution metrics; set log retention."},
  ('AWS', 'CodeBuild'): {"apis": ["codebuild:ListProjects", "codebuild:ListBuildsForProject(projectName='<each>')", "ce:GetCostAndUsage(Filter={SERVICE:['AWS CodeBuild']},GroupBy=USAGE_TYPE)"], "drilldownInstructions": "Charged per build-minute by compute type. Right-size build compute, enable caching to shorten builds, and remove projects with no recent builds."},
  ('AWS', 'Cognito'): {"apis": ["cognito-idp:ListUserPools(MaxResults=60)", "cognito-idp:DescribeUserPool(UserPoolId='<each>')", "ce:GetCostAndUsage(Filter={SERVICE:['Amazon Cognito']},GroupBy=USAGE_TYPE)"], "drilldownInstructions": "Cost driven by monthly active users and advanced security. Disable advanced security if unused; review MAU tier; remove abandoned user pools."},
  ('AWS', 'ECS'): {"apis": ["ecs:ListClusters", "ecs:ListServices(cluster='<each>')", "ecs:DescribeServices", "cloudwatch:GetMetricStatistics(Namespace='AWS/ECS',MetricName='CPUUtilization')"], "drilldownInstructions": "Check Fargate task CPU/memory vs requested. Right-size task definitions, use Fargate Spot for non-critical tasks (up to 70% off), and scale services to zero off-hours."},
  ('AWS', 'EFS'): {"apis": ["efs:DescribeFileSystems", "efs:DescribeLifecycleConfiguration(FileSystemId='<each>')", "cloudwatch:GetMetricStatistics(Namespace='AWS/EFS',MetricName='TotalIOBytes')"], "drilldownInstructions": "Enable lifecycle management to move idle files to Infrequent Access (up to 92% cheaper). Check throughput mode (Provisioned vs Bursting) and idle file systems."},
  ('AWS', 'EMR'): {"apis": ["emr:ListClusters(ClusterStates=['RUNNING','WAITING'])", "emr:ListInstanceGroups(ClusterId='<each>')", "ce:GetCostAndUsage(Filter={SERVICE:['Amazon Elastic MapReduce']},GroupBy=USAGE_TYPE)"], "drilldownInstructions": "Find long-running/idle clusters. Use Spot for task nodes, enable managed scaling, and prefer transient clusters or EMR Serverless for batch jobs."},
  ('AWS', 'EventBridge'): {"apis": ["events:ListRules", "events:ListEventBuses", "ce:GetCostAndUsage(Filter={SERVICE:['Amazon EventBridge']},GroupBy=USAGE_TYPE)"], "drilldownInstructions": "Custom events are $1/million; archives/replay add storage. Remove unused rules, reduce schema-discovery, and audit cross-account event volume."},
  ('AWS', 'GuardDuty'): {"apis": ["guardduty:ListDetectors", "guardduty:GetDetector(DetectorId='<each>')", "ce:GetCostAndUsage(Filter={SERVICE:['Amazon GuardDuty']},GroupBy=USAGE_TYPE)"], "drilldownInstructions": "Cost scales with CloudTrail events, VPC Flow Logs, and DNS analyzed. Disable protection plans you don't use (e.g., S3/Malware) and review high-volume event sources."},
  ('AWS', 'IAM'): {"apis": ["iam:GenerateCredentialReport", "iam:GetCredentialReport", "iam:ListUsers", "iam:ListRoles"], "drilldownInstructions": "IAM is free but drives security hygiene: find unused users/keys/roles (no activity >90d via credential report) and remove them to reduce blast radius (no direct cost)."},
  ('AWS', 'Kinesis'): {"apis": ["kinesis:ListStreams", "kinesis:DescribeStreamSummary(StreamName='<each>')", "ce:GetCostAndUsage(Filter={SERVICE:['Amazon Kinesis']},GroupBy=USAGE_TYPE)"], "drilldownInstructions": "Provisioned shards cost $/shard-hour. Switch low/variable throughput streams to On-Demand, reduce over-provisioned shards, and shorten extended retention."},
  ('AWS', 'MSK'): {"apis": ["kafka:ListClustersV2", "kafka:DescribeClusterV2(ClusterArn='<each>')", "cloudwatch:GetMetricStatistics(Namespace='AWS/Kafka',MetricName='CPUUtilization')"], "drilldownInstructions": "Right-size broker instance types and broker count by CPU/throughput. Consider MSK Serverless for spiky workloads and tiered storage to cut broker storage."},
  ('AWS', 'OpenSearch'): {"apis": ["opensearch:ListDomainNames", "opensearch:DescribeDomain(DomainName='<each>')", "cloudwatch:GetMetricStatistics(Namespace='AWS/ES',MetricName='CPUUtilization')"], "drilldownInstructions": "Check node CPU/storage utilization. Right-size data nodes, use UltraWarm/cold storage for old indices, and buy Reserved Instances for steady-state domains."},
  ('AWS', 'Redshift'): {"apis": ["redshift:DescribeClusters", "cloudwatch:GetMetricStatistics(Namespace='AWS/Redshift',MetricName='CPUUtilization')", "ce:GetReservationPurchaseRecommendation(Service='AmazonRedshift')"], "drilldownInstructions": "Find idle/over-provisioned clusters. Pause+resume or use Redshift Serverless for intermittent use; apply Reserved Instances for steady-state; enable concurrency scaling limits."},
  ('AWS', 'SES'): {"apis": ["ses:GetSendStatistics", "ses:ListIdentities", "ce:GetCostAndUsage(Filter={SERVICE:['Amazon Simple Email Service']},GroupBy=USAGE_TYPE)"], "drilldownInstructions": "Cost is per-email + data. Reduce bounce/complaint waste, consolidate dedicated IPs if under-utilized, and remove unused configuration sets/identities."},
  ('AWS', 'SNS'): {"apis": ["sns:ListTopics", "sns:GetTopicAttributes(TopicArn='<each>')", "ce:GetCostAndUsage(Filter={SERVICE:['Amazon Simple Notification Service']},GroupBy=USAGE_TYPE)"], "drilldownInstructions": "SMS and cross-region delivery dominate cost. Audit SMS spend, prefer email/HTTPS where possible, and delete unused topics/subscriptions."},
  ('AWS', 'SQS'): {"apis": ["sqs:ListQueues", "sqs:GetQueueAttributes(QueueUrl='<each>')", "cloudwatch:GetMetricStatistics(Namespace='AWS/SQS',MetricName='NumberOfMessagesSent')"], "drilldownInstructions": "Charged per request (FIFO costs more). Batch sends/receives, enable long polling to cut empty receives, and remove idle queues."},
  ('AWS', 'Secrets Manager'): {"apis": ["secretsmanager:ListSecrets", "ce:GetCostAndUsage(Filter={SERVICE:['AWS Secrets Manager']},GroupBy=USAGE_TYPE)"], "drilldownInstructions": "Each secret is $0.40/mo + API calls. Delete unused secrets, consolidate related values into one secret, and consider SSM Parameter Store (free standard tier) for non-rotating config."},
  ('AWS', 'Shield'): {"apis": ["shield:DescribeSubscription", "shield:ListProtections", "ce:GetCostAndUsage(Filter={SERVICE:['AWS Shield']},GroupBy=USAGE_TYPE)"], "drilldownInstructions": "Shield Advanced is $3,000/mo committed. Confirm it's justified vs Shield Standard (free); ensure all protected resources are actually high-value/internet-facing."},
  ('AWS', 'Step Functions'): {"apis": ["states:ListStateMachines", "states:ListExecutions(stateMachineArn='<each>')", "ce:GetCostAndUsage(Filter={SERVICE:['AWS Step Functions']},GroupBy=USAGE_TYPE)"], "drilldownInstructions": "Standard workflows charge per state transition. Switch high-volume short workflows to Express ($/duration), and reduce unnecessary states/retries."},
  ('AWS', 'Systems Manager'): {"apis": ["ssm:DescribeParameters", "ssm:DescribeInstanceInformation", "ce:GetCostAndUsage(Filter={SERVICE:['AWS Systems Manager']},GroupBy=USAGE_TYPE)"], "drilldownInstructions": "Advanced Parameters ($0.05/mo each) and high API throughput cost money. Downgrade unused advanced parameters to standard and audit automation throughput."},
  ('AWS', 'Transfer Family'): {"apis": ["transfer:ListServers", "transfer:ListUsers(ServerId='<each>')", "ce:GetCostAndUsage(Filter={SERVICE:['AWS Transfer Family']},GroupBy=USAGE_TYPE)"], "drilldownInstructions": "Each enabled endpoint is ~$0.30/hr ($216/mo) plus data. Stop endpoints when idle, consolidate protocols onto one server, or use S3 directly where SFTP isn't required."},
  ('AWS', 'WAF'): {"apis": ["wafv2:ListWebACLs(Scope='REGIONAL')", "wafv2:GetWebACL", "ce:GetCostAndUsage(Filter={SERVICE:['AWS WAF']},GroupBy=USAGE_TYPE)"], "drilldownInstructions": "Charged per Web ACL ($5/mo), per rule ($1/mo), and per request. Remove unused/duplicate rules and managed rule groups; consolidate ACLs."},
  ('AWS', 'WorkSpaces'): {"apis": ["workspaces:DescribeWorkspaces", "workspaces:DescribeWorkspacesConnectionStatus", "cloudwatch:GetMetricStatistics(Namespace='AWS/WorkSpaces',MetricName='UserConnected')"], "drilldownInstructions": "Find WorkSpaces with no recent connection (pure waste). Switch always-on (monthly) billing to AutoStop (hourly) for part-time users; terminate unused desktops."},
  ('AWS', 'OpenAI'): {"apis": ["ce:GetCostAndUsage(GroupBy=SERVICE)"], "drilldownInstructions": "This tip is mis-tagged under AWS; treat as a generic cost breakdown. Use Cost Explorer to identify the actual top services and investigate the largest spenders."},

  # ---------------- AZURE ----------------
  ('AZURE', 'Application Insights'): {"apis": ["az monitor app-insights component show", "az monitor log-analytics workspace list", "az consumption usage list --query \"[?contains(meterCategory,'Application Insights')]\""], "drilldownInstructions": "Ingestion is billed per GB. Set a daily cap, enable sampling, and reduce verbose custom telemetry. Move long retention to cheaper Log Analytics archive."},
  ('AZURE', 'Azure Database for MySQL'): {"apis": ["az mysql flexible-server list", "az monitor metrics list --metric cpu_percent --interval P14D --aggregation Average", "az monitor metrics list --metric active_connections --aggregation Maximum"], "drilldownInstructions": "Check 14-day CPU/connections. Move <20% CPU General Purpose servers to Burstable; stop/start dev-test; apply Reserved Capacity for steady-state."},
  ('AZURE', 'Azure Functions'): {"apis": ["az functionapp list", "az monitor metrics list --metric FunctionExecutionCount --aggregation Total", "az consumption usage list --query \"[?contains(meterCategory,'Functions')]\""], "drilldownInstructions": "On Premium/Dedicated plans, check utilization and downsize; for spiky/low traffic move to Consumption plan (pay per execution). Delete zero-invocation functions."},
  ('AZURE', 'Azure Monitor'): {"apis": ["az monitor log-analytics workspace list", "az monitor log-analytics workspace show --query 'retentionInDays'", "az consumption usage list --query \"[?contains(meterCategory,'Log Analytics') || contains(meterCategory,'Monitor')]\""], "drilldownInstructions": "Log Analytics is billed per GB ingested + retention. Set ingestion caps, enable Basic Logs for high-volume tables, reduce retention, and add data-collection filters."},
  ('AZURE', 'Azure Policy'): {"apis": ["az policy assignment list", "az policy state summarize", "az advisor recommendation list --category Cost"], "drilldownInstructions": "Policy itself is free; use it to enforce cost guardrails. Add deny/audit policies for oversized SKUs, required tags, and allowed regions to prevent future waste."},
  ('AZURE', 'Azure Synapse'): {"apis": ["az synapse workspace list", "az synapse sql pool list --workspace-name <ws>", "az monitor metrics list --metric DWULimit"], "drilldownInstructions": "Pause dedicated SQL pools when idle (compute billed while online). Right-size DWU, set auto-pause for serverless, and cap serverless SQL data-scanned spend."},
  ('AZURE', 'Container Instances'): {"apis": ["az container list", "az container show --name <each> --query 'containers[].resources.requests'", "az consumption usage list --query \"[?contains(meterCategory,'Container Instances')]\""], "drilldownInstructions": "Billed per vCPU/GB-second while running. Stop/delete idle container groups, right-size CPU/memory requests, and use spot/scheduled runs for batch."},
  ('AZURE', 'DDoS Protection'): {"apis": ["az network ddos-protection list", "az network vnet list --query \"[?enableDdosProtection]\""], "drilldownInstructions": "DDoS Network Protection is ~$2,944/mo per plan covering 100 public IPs. Ensure one plan covers all VNets (don't duplicate); confirm it's required vs free Basic protection."},
  ('AZURE', 'Data Factory'): {"apis": ["az datafactory list", "az datafactory pipeline-run query-by-factory", "az consumption usage list --query \"[?contains(meterCategory,'Data Factory')]\""], "drilldownInstructions": "Cost = pipeline activity runs + Data Integration Units + SSIS IR uptime. Pause/right-size SSIS IR, reduce trigger frequency, and consolidate copy activities."},
  ('AZURE', 'Data Lake Storage'): {"apis": ["az storage account list --query \"[?isHnsEnabled]\"", "az storage account management-policy show --account-name <each>", "az monitor metrics list --metric UsedCapacity --interval P30D"], "drilldownInstructions": "Apply lifecycle policies to tier cold data to Cool/Archive (up to 90% cheaper). Check redundancy (GRS->LRS) and remove obsolete datasets."},
  ('AZURE', 'Event Hubs'): {"apis": ["az eventhubs namespace list", "az eventhubs eventhub list --namespace-name <ns>", "az monitor metrics list --metric IncomingMessages --aggregation Total"], "drilldownInstructions": "Right-size Throughput Units (Standard) or Processing Units (Premium); enable Auto-Inflate with a max; drop unused namespaces and shorten capture retention."},
  ('AZURE', 'ExpressRoute'): {"apis": ["az network express-route list", "az network express-route show --query '{sku:sku,bandwidth:serviceProviderProperties.bandwidthInMbps}'", "az monitor metrics list --metric BitsInPerSecond"], "drilldownInstructions": "Match circuit bandwidth and SKU (Standard vs Premium) to actual utilization. Switch Metered to Unlimited only if egress is high; remove idle circuits."},
  ('AZURE', 'Governance'): {"apis": ["az account management-group list", "az policy assignment list", "az advisor recommendation list --category Cost"], "drilldownInstructions": "Use management groups + policy + budgets to enforce org-wide cost control. Apply tag governance and Advisor remediation across subscriptions."},
  ('AZURE', 'Key Vault'): {"apis": ["az keyvault list", "az monitor metrics list --metric ServiceApiHit --aggregation Total", "az consumption usage list --query \"[?contains(meterCategory,'Key Vault')]\""], "drilldownInstructions": "Operations and HSM keys cost money (Premium HSM keys ~$1/key/mo + per-operation). Reduce secret/operation churn, remove unused vaults, and use Standard tier where HSM isn't required."},
  ('AZURE', 'Managed Disks'): {"apis": ["az disk list --query \"[?diskState=='Unattached']\"", "az disk list --query '[].{name:name,sku:sku.name,sizeGb:diskSizeGb}'", "az snapshot list"], "drilldownInstructions": "Delete unattached disks (pure waste). Downgrade over-provisioned Premium SSD to Standard SSD/HDD where IOPS allow; clean up old snapshots."},
  ('AZURE', 'Networking'): {"apis": ["az network public-ip list --query \"[?ipConfiguration==null]\"", "az network nat gateway list", "az consumption usage list --query \"[?contains(meterCategory,'Bandwidth') || contains(meterCategory,'Virtual Network')]\""], "drilldownInstructions": "Release unassociated public IPs, review NAT gateway data-processing charges, and reduce inter-region/egress bandwidth. Use Private Endpoints/Service Endpoints where cheaper."},
  ('AZURE', 'Service Bus'): {"apis": ["az servicebus namespace list", "az servicebus queue list --namespace-name <ns>", "az monitor metrics list --metric IncomingMessages --aggregation Total"], "drilldownInstructions": "Downgrade idle Premium messaging units to Standard; remove unused namespaces/queues/topics; right-size Premium MUs to throughput."},
  ('AZURE', 'Site Recovery'): {"apis": ["az backup vault list", "az site-recovery vault list", "az consumption usage list --query \"[?contains(meterCategory,'Site Recovery')]\""], "drilldownInstructions": "~$25/mo per protected instance + target storage/compute. Remove decommissioned machines from replication and use lower-cost target storage tiers."},
  ('AZURE', 'VM Scale Sets'): {"apis": ["az vmss list", "az vmss show --query '{sku:sku,capacity:sku.capacity,overprovision:overprovision}'", "az monitor metrics list --metric 'Percentage CPU' --interval P7D --aggregation Average"], "drilldownInstructions": "Enable autoscaling instead of fixed capacity, use Spot priority for non-critical sets (up to 90% off), and right-size the VM SKU by CPU."},
  ('AZURE', 'VPN Gateway'): {"apis": ["az network vnet-gateway list", "az network vnet-gateway show --query 'sku.name'", "az monitor metrics list --metric AverageBandwidth"], "drilldownInstructions": "Match gateway SKU (VpnGw1-5) to actual throughput. Downgrade over-sized gateways and delete idle ones; consider lower-cost Basic SKU for dev/test."},
  ('AZURE', 'Web Application Firewall'): {"apis": ["az network application-gateway waf-policy list", "az network front-door waf-policy list", "az monitor metrics list --metric TotalRequests"], "drilldownInstructions": "WAF adds per-policy + per-request cost on App Gateway/Front Door. Remove duplicate/unused policies, consolidate, and disable rule sets you don't enforce."},

  # ---------------- GCP ----------------
  ('GCP', 'Apigee'): {"apis": ["gcloud apigee organizations list", "gcloud apigee environments list --organization=<org>", "gcloud billing accounts list"], "drilldownInstructions": "Apigee (esp. legacy Pay-as-you-go/Subscription) has high base cost. Right-size environments, remove unused environments/orgs, and confirm the pricing tier matches API traffic."},
  ('GCP', 'Backup'): {"apis": ["gcloud backup-dr backup-vaults list", "gcloud compute snapshots list", "gcloud sql backups list --instance=<inst>"], "drilldownInstructions": "Reduce snapshot/backup retention, delete orphaned snapshots of deleted disks, and store long-term backups in cheaper storage classes."},
  ('GCP', 'Bigtable'): {"apis": ["gcloud bigtable instances list", "gcloud bigtable clusters list", "gcloud monitoring (bigtable.googleapis.com/cluster/cpu_load)"], "drilldownInstructions": "Match node count to CPU load (<70% target). Enable autoscaling, drop dev instances to development (single-node) tier, and remove idle instances."},
  ('GCP', 'Cloud Armor'): {"apis": ["gcloud compute security-policies list", "gcloud compute security-policies describe <policy>"], "drilldownInstructions": "Charged per policy + per rule + per request. Consolidate policies, remove unused rules, and confirm Managed Protection Plus tier is justified."},
  ('GCP', 'Cloud Build'): {"apis": ["gcloud builds list --limit=50", "gcloud builds triggers list"], "drilldownInstructions": "Billed per build-minute by machine type. Use the free default pool where possible, cache dependencies, right-size machine type, and remove redundant triggers."},
  ('GCP', 'Cloud CDN'): {"apis": ["gcloud compute backend-services list --filter='enableCDN=true'", "gcloud monitoring (loadbalancing.googleapis.com/https/request_count)"], "drilldownInstructions": "Improve cache hit ratio (tune TTL/cache keys) to cut origin egress. Review cache-fill cross-region costs and disable CDN on backends that don't benefit."},
  ('GCP', 'Cloud DNS'): {"apis": ["gcloud dns managed-zones list", "gcloud dns record-sets list --zone=<zone>"], "drilldownInstructions": "Billed per zone + per query. Delete unused zones, consolidate, and reduce health-check/query volume from misconfigured clients."},
  ('GCP', 'Cloud Interconnect'): {"apis": ["gcloud compute interconnects list", "gcloud compute interconnects attachments list", "gcloud monitoring (interconnect capacity)"], "drilldownInstructions": "Match VLAN attachment capacity to utilization. Remove idle attachments/interconnects and review egress routed over interconnect vs internet."},
  ('GCP', 'Cloud Monitoring'): {"apis": ["gcloud monitoring dashboards list", "gcloud logging metrics list"], "drilldownInstructions": "Chargeable metrics ingestion beyond free allotment. Reduce custom/agent metric cardinality and frequency; drop unused metric descriptors."},
  ('GCP', 'Cloud NAT'): {"apis": ["gcloud compute routers nats list --router=<router> --region=<region>", "gcloud monitoring (router.googleapis.com/nat/sent_bytes_count)"], "drilldownInstructions": "Billed per NAT gateway-hour + data processed. Use Private Google Access for Google APIs (free), and remove NAT in subnets that don't need egress."},
  ('GCP', 'Cloud Trace'): {"apis": ["gcloud services list --filter='cloudtrace'", "gcloud monitoring (spans ingested)"], "drilldownInstructions": "Billed per span ingested beyond free tier. Lower trace sampling rate for high-traffic services to cut ingestion."},
  ('GCP', 'Dataflow'): {"apis": ["gcloud dataflow jobs list --status=active", "gcloud monitoring (dataflow vCPU/memory)"], "drilldownInstructions": "Right-size worker machine type and max workers; enable autoscaling and FlexRS for batch (lower cost); cancel stuck/idle streaming jobs."},
  ('GCP', 'Dataproc'): {"apis": ["gcloud dataproc clusters list --region=<region>", "gcloud dataproc jobs list --region=<region>"], "drilldownInstructions": "Use ephemeral/autoscaling clusters and Spot (preemptible) secondary workers; enable cluster auto-delete TTL; prefer Serverless for Spark batch."},
  ('GCP', 'Filestore'): {"apis": ["gcloud filestore instances list", "gcloud monitoring (filestore used_bytes)"], "drilldownInstructions": "Filestore bills per provisioned GB by tier. Downsize over-provisioned Premium/Enterprise tiers to Basic/Zonal where IOPS allow; delete idle shares."},
  ('GCP', 'Firestore'): {"apis": ["gcloud firestore databases list", "gcloud monitoring (firestore document reads/writes)"], "drilldownInstructions": "Cost is per read/write/delete + storage. Reduce read amplification with caching/denormalization, add TTL policies to expire stale docs, and remove unused indexes."},
  ('GCP', 'Governance'): {"apis": ["gcloud organizations list", "gcloud resource-manager org-policies list --organization=<org>", "gcloud billing budgets list"], "drilldownInstructions": "Apply org policies, budgets/alerts, and label governance across projects to prevent waste (no direct cost)."},
  ('GCP', 'Memorystore'): {"apis": ["gcloud redis instances list --region=<region>", "gcloud monitoring (redis.googleapis.com/stats/memory/usage_ratio)"], "drilldownInstructions": "Downsize instances with low memory-usage ratio, use Basic tier for dev (no replica), and delete idle instances."},
  ('GCP', 'Persistent Disks'): {"apis": ["gcloud compute disks list --filter='-users:*'", "gcloud compute disks list --format='table(name,sizeGb,type)'", "gcloud compute snapshots list"], "drilldownInstructions": "Delete unattached disks (still billed), downgrade SSD (pd-ssd) to Balanced/Standard where IOPS allow, and clean up old snapshots/images."},
  ('GCP', 'Secret Manager'): {"apis": ["gcloud secrets list", "gcloud secrets versions list <secret>"], "drilldownInstructions": "Billed per active secret version + access operations. Destroy old/unused secret versions, remove unused secrets, and cache reads to cut access ops."},
  ('GCP', 'Speech-to-Text'): {"apis": ["gcloud ml speech (usage via billing export)", "BigQuery billing export (service.description='Speech-to-Text')"], "drilldownInstructions": "Billed per audio-minute. Use the standard (vs enhanced) model where accuracy allows, trim silence before sending, and batch where possible."},
  ('GCP', 'Vertex AI'): {"apis": ["gcloud ai endpoints list --region=<region>", "gcloud ai models list --region=<region>", "gcloud monitoring (prediction request_count)"], "drilldownInstructions": "Undeploy endpoints with zero traffic (nodes billed while deployed), right-size machine type/min-replicas, and use batch prediction for non-realtime."},
  ('GCP', 'Vision AI'): {"apis": ["BigQuery billing export (service.description='Cloud Vision API')", "gcloud monitoring (vision request_count)"], "drilldownInstructions": "Billed per 1,000 feature-units. Request only the features you need per image, batch requests, and cache results for repeated images."},
}
