content = open('members/index.html', 'r', encoding='utf-8').read()

old = '<!-- Step 4: Test Connection -->\n                <div id="wiz-step-4" class="wizard-step-content" hidden>\n                    <div class="wizard-icon">&#9889;</div>\n                    <h3>Step 4: Test the Connection</h3>\n                    <p>Let\'s verify that SlashMyBill can access your AWS account\'s billing data through the role you just created.</p>\n                    <div id="wiz-test-result" class="wizard-test-result" hidden></div>\n                    <button id="wiz-test-btn" class="btn btn-primary btn-full">\n                        &#9889; Test Connection\n                    </button>\n                    <div class="wizard-note">This will attempt to assume the IAM role and read your Cost Explorer data.</div>\n                </div>'

new = '<!-- Step 4: Test Connection + Hourly Check -->\n                <div id="wiz-step-4" class="wizard-step-content" hidden>\n                    <div class="wizard-icon">&#9889;</div>\n                    <h3>Step 4: Test &amp; Configure</h3>\n                    <p>Verify the connection and optionally enable hourly cost tracking for real-time insights.</p>\n                    <div id="wiz-test-result" class="wizard-test-result" hidden></div>\n                    <button id="wiz-test-btn" class="btn btn-primary btn-full">\n                        &#9889; Test Connection\n                    </button>\n                    <div class="wizard-note" style="margin-bottom:16px;">This will attempt to assume the IAM role and read your Cost Explorer data.</div>\n                    <div id="wiz-hourly-section" style="border-top:1px solid #e5e7eb;padding-top:16px;margin-top:4px;">\n                        <div style="font-weight:600;color:#1f2937;margin-bottom:6px;">&#9201; Hourly Cost Tracking <span style="font-size:11px;color:#6b7280;font-weight:400;">(optional, recommended)</span></div>\n                        <p style="font-size:0.85em;color:#6b7280;margin:0 0 10px;">Enables real-time hourly cost charts. Must be enabled manually in AWS Cost Explorer Settings (management account only).</p>\n                        <div id="wiz-hourly-status" style="margin-bottom:10px;"></div>\n                        <div style="display:flex;gap:8px;flex-wrap:wrap;">\n                            <button id="wiz-check-hourly-btn" class="btn btn-outline btn-sm" style="font-size:13px;">Check Hourly Status</button>\n                            <a href="https://us-east-1.console.aws.amazon.com/cost-management/home?region=us-east-1#/settings" target="_blank" rel="noopener" class="btn btn-outline btn-sm" style="font-size:13px;text-decoration:none;">Open CE Settings &#8599;</a>\n                        </div>\n                    </div>\n                </div>'

if old in content:
    content = content.replace(old, new)
    open('members/index.html', 'w', encoding='utf-8').write(content)
    print('SUCCESS: wizard step 4 updated')
else:
    print('NOT FOUND - checking snippet...')
    idx = content.find('wiz-step-4')
    print(repr(content[idx:idx+500]))
