"""Unit tests for HCL round-trip parsing and ActionDefinition.

Tests cover:
- HclDocument.parse() can reconstruct blocks from rendered HCL
- ActionDefinition round-trip: create -> to_hcl -> from_hcl -> compare
"""

import sys
import os

# Add parent directory to path for imports
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from hcl_generator.core import (
    HclBlock,
    HclDocument,
    HclRawExpression,
    render_provider_block,
)
from hcl_generator.models import ActionDefinition


class TestHclDocumentParse:
    """Tests for HclDocument.parse()."""

    def test_parse_simple_block_no_labels(self):
        """Parse a simple block with no labels."""
        doc = HclDocument(blocks=[
            HclBlock(block_type="terraform", attributes={"required_version": ">= 1.5"})
        ])
        rendered = doc.render()
        parsed = HclDocument.parse(rendered)

        assert len(parsed.blocks) == 1
        assert parsed.blocks[0].block_type == "terraform"
        assert parsed.blocks[0].attributes["required_version"] == ">= 1.5"
        assert parsed.blocks[0].labels == []

    def test_parse_block_with_labels(self):
        """Parse a resource block with two labels."""
        doc = HclDocument(blocks=[
            HclBlock(
                block_type="resource",
                labels=["aws_instance", "main"],
                attributes={"instance_type": "t3.medium"},
            )
        ])
        rendered = doc.render()
        parsed = HclDocument.parse(rendered)

        assert len(parsed.blocks) == 1
        assert parsed.blocks[0].block_type == "resource"
        assert parsed.blocks[0].labels == ["aws_instance", "main"]
        assert parsed.blocks[0].attributes["instance_type"] == "t3.medium"

    def test_parse_header_comment(self):
        """Parse header comments correctly."""
        doc = HclDocument(
            blocks=[HclBlock(block_type="terraform")],
            header_comment="Generated by SlashMyBill\nDo not edit manually",
        )
        rendered = doc.render()
        parsed = HclDocument.parse(rendered)

        assert parsed.header_comment == "Generated by SlashMyBill\nDo not edit manually"

    def test_parse_header_comment_with_empty_lines(self):
        """Parse header comments with empty lines."""
        doc = HclDocument(
            blocks=[HclBlock(block_type="terraform")],
            header_comment="Line 1\n\nLine 3",
        )
        rendered = doc.render()
        parsed = HclDocument.parse(rendered)

        assert parsed.header_comment == "Line 1\n\nLine 3"

    def test_parse_boolean_attributes(self):
        """Parse boolean attribute values."""
        doc = HclDocument(blocks=[
            HclBlock(
                block_type="resource",
                labels=["aws_instance", "test"],
                attributes={"monitoring": True, "disable_api_termination": False},
            )
        ])
        rendered = doc.render()
        parsed = HclDocument.parse(rendered)

        assert parsed.blocks[0].attributes["monitoring"] is True
        assert parsed.blocks[0].attributes["disable_api_termination"] is False

    def test_parse_numeric_attributes(self):
        """Parse integer attribute values."""
        doc = HclDocument(blocks=[
            HclBlock(
                block_type="resource",
                labels=["aws_ebs_volume", "data"],
                attributes={"size": 100, "iops": 3000},
            )
        ])
        rendered = doc.render()
        parsed = HclDocument.parse(rendered)

        assert parsed.blocks[0].attributes["size"] == 100
        assert parsed.blocks[0].attributes["iops"] == 3000

    def test_parse_list_attribute(self):
        """Parse list attribute values."""
        doc = HclDocument(blocks=[
            HclBlock(
                block_type="variable",
                labels=["tags"],
                attributes={"default": ["web", "production"]},
            )
        ])
        rendered = doc.render()
        parsed = HclDocument.parse(rendered)

        assert parsed.blocks[0].attributes["default"] == ["web", "production"]

    def test_parse_map_attribute(self):
        """Parse map/dict attribute values."""
        doc = HclDocument(blocks=[
            HclBlock(
                block_type="resource",
                labels=["aws_instance", "main"],
                attributes={"tags": {"Name": "my-instance", "Environment": "prod"}},
            )
        ])
        rendered = doc.render()
        parsed = HclDocument.parse(rendered)

        assert parsed.blocks[0].attributes["tags"] == {
            "Name": "my-instance",
            "Environment": "prod",
        }

    def test_parse_nested_blocks(self):
        """Parse blocks with nested blocks."""
        inner = HclBlock(
            block_type="assume_role",
            attributes={"role_arn": "arn:aws:iam::123456789012:role/MyRole"},
        )
        outer = HclBlock(
            block_type='provider "aws"',
            attributes={"region": "us-east-1"},
            nested_blocks=[inner],
        )
        doc = HclDocument(blocks=[outer])
        rendered = doc.render()
        parsed = HclDocument.parse(rendered)

        assert len(parsed.blocks) == 1
        assert parsed.blocks[0].block_type == 'provider "aws"'
        assert parsed.blocks[0].attributes["region"] == "us-east-1"
        assert len(parsed.blocks[0].nested_blocks) == 1
        assert parsed.blocks[0].nested_blocks[0].block_type == "assume_role"
        assert parsed.blocks[0].nested_blocks[0].attributes["role_arn"] == (
            "arn:aws:iam::123456789012:role/MyRole"
        )

    def test_parse_raw_expression(self):
        """Parse raw expressions (unquoted values)."""
        doc = HclDocument(blocks=[
            HclBlock(
                block_type="import",
                labels=[],
                attributes={
                    "to": HclRawExpression("aws_instance.main"),
                    "id": "i-0abc123",
                },
            )
        ])
        rendered = doc.render()
        parsed = HclDocument.parse(rendered)

        assert parsed.blocks[0].block_type == "import"
        # Raw expression should be parsed back as HclRawExpression
        to_val = parsed.blocks[0].attributes["to"]
        assert isinstance(to_val, HclRawExpression)
        assert to_val.expression == "aws_instance.main"
        # String value should be parsed as string
        assert parsed.blocks[0].attributes["id"] == "i-0abc123"

    def test_parse_multiple_blocks(self):
        """Parse a document with multiple top-level blocks."""
        doc = HclDocument(blocks=[
            HclBlock(block_type="terraform"),
            HclBlock(
                block_type='provider "aws"',
                attributes={"region": "us-east-1"},
            ),
            HclBlock(
                block_type="resource",
                labels=["aws_instance", "main"],
                attributes={"instance_type": "t3.medium"},
            ),
        ])
        rendered = doc.render()
        parsed = HclDocument.parse(rendered)

        assert len(parsed.blocks) == 3
        assert parsed.blocks[0].block_type == "terraform"
        assert parsed.blocks[1].block_type == 'provider "aws"'
        assert parsed.blocks[2].block_type == "resource"
        assert parsed.blocks[2].labels == ["aws_instance", "main"]

    def test_parse_empty_list(self):
        """Parse empty list attribute."""
        doc = HclDocument(blocks=[
            HclBlock(
                block_type="variable",
                labels=["empty"],
                attributes={"default": []},
            )
        ])
        rendered = doc.render()
        parsed = HclDocument.parse(rendered)

        assert parsed.blocks[0].attributes["default"] == []

    def test_parse_empty_map(self):
        """Parse empty map attribute."""
        doc = HclDocument(blocks=[
            HclBlock(
                block_type="variable",
                labels=["empty_map"],
                attributes={"default": {}},
            )
        ])
        rendered = doc.render()
        parsed = HclDocument.parse(rendered)

        assert parsed.blocks[0].attributes["default"] == {}

    def test_parse_escaped_string(self):
        """Parse strings with escaped characters."""
        doc = HclDocument(blocks=[
            HclBlock(
                block_type="variable",
                labels=["test"],
                attributes={"default": 'say "hello"'},
            )
        ])
        rendered = doc.render()
        parsed = HclDocument.parse(rendered)

        assert parsed.blocks[0].attributes["default"] == 'say "hello"'

    def test_parse_string_with_interpolation(self):
        """Parse strings with escaped interpolation sequences."""
        doc = HclDocument(blocks=[
            HclBlock(
                block_type="variable",
                labels=["test"],
                attributes={"default": "value is ${var.name}"},
            )
        ])
        rendered = doc.render()
        parsed = HclDocument.parse(rendered)

        assert parsed.blocks[0].attributes["default"] == "value is ${var.name}"

    def test_parse_removed_block(self):
        """Parse a removed {} block with nested lifecycle."""
        lifecycle_block = HclBlock(
            block_type="lifecycle",
            labels=[],
            attributes={"destroy": True},
        )
        removed_block = HclBlock(
            block_type="removed",
            labels=[],
            attributes={
                "from": HclRawExpression("aws_ebs_volume.vol_abc123"),
            },
            nested_blocks=[lifecycle_block],
        )
        doc = HclDocument(blocks=[removed_block])
        rendered = doc.render()
        parsed = HclDocument.parse(rendered)

        assert len(parsed.blocks) == 1
        assert parsed.blocks[0].block_type == "removed"
        from_val = parsed.blocks[0].attributes["from"]
        assert isinstance(from_val, HclRawExpression)
        assert from_val.expression == "aws_ebs_volume.vol_abc123"
        assert len(parsed.blocks[0].nested_blocks) == 1
        assert parsed.blocks[0].nested_blocks[0].block_type == "lifecycle"
        assert parsed.blocks[0].nested_blocks[0].attributes["destroy"] is True

    def test_parse_full_resize_ec2_document(self):
        """Parse a complete resize EC2 document (realistic scenario)."""
        from hcl_generator.actions import generate_action_hcl

        doc = generate_action_hcl(
            action_type="resize-ec2",
            action_params={
                "instanceId": "i-0abc123def",
                "targetInstanceType": "t3.medium",
            },
            account_id="123456789012",
            region="us-east-1",
        )
        rendered = doc.render()
        parsed = HclDocument.parse(rendered)

        # Should have header comment
        assert "Generated by SlashMyBill" in parsed.header_comment
        assert "Resize EC2" in parsed.header_comment

        # Should have terraform, provider, resource, and import blocks
        block_types = [b.block_type for b in parsed.blocks]
        assert "terraform" in block_types
        assert 'provider "aws"' in block_types
        assert "resource" in block_types
        assert "import" in block_types

        # Find the resource block
        resource_block = next(b for b in parsed.blocks if b.block_type == "resource")
        assert resource_block.labels[0] == "aws_instance"
        assert resource_block.attributes["instance_type"] == "t3.medium"

    def test_parse_full_delete_ebs_document(self):
        """Parse a complete delete EBS document with removed block."""
        from hcl_generator.actions import generate_action_hcl

        doc = generate_action_hcl(
            action_type="delete-ebs",
            action_params={"volumeId": "vol-0abc123"},
            account_id="123456789012",
            region="us-east-1",
        )
        rendered = doc.render()
        parsed = HclDocument.parse(rendered)

        # Should have removed block
        removed_blocks = [b for b in parsed.blocks if b.block_type == "removed"]
        assert len(removed_blocks) == 1
        from_val = removed_blocks[0].attributes["from"]
        assert isinstance(from_val, HclRawExpression)
        assert "aws_ebs_volume" in from_val.expression

    def test_roundtrip_render_parse_render(self):
        """Render -> parse -> render should produce identical output."""
        original_doc = HclDocument(
            blocks=[
                HclBlock(
                    block_type="terraform",
                    nested_blocks=[
                        HclBlock(
                            block_type="required_providers",
                            nested_blocks=[
                                HclBlock(
                                    block_type="aws",
                                    attributes={
                                        "source": "hashicorp/aws",
                                        "version": ">= 5.0",
                                    },
                                )
                            ],
                        )
                    ],
                ),
                HclBlock(
                    block_type="resource",
                    labels=["aws_instance", "main"],
                    attributes={
                        "instance_type": "t3.medium",
                        "tags": {"Name": "test", "Env": "prod"},
                    },
                ),
            ],
            header_comment="Test header\nSecond line",
        )
        rendered1 = original_doc.render()
        parsed = HclDocument.parse(rendered1)
        rendered2 = parsed.render()

        assert rendered1 == rendered2


class TestActionDefinitionToHcl:
    """Tests for ActionDefinition.to_hcl()."""

    def test_resource_action_generates_resource_and_import(self):
        """A non-removal action generates resource + import blocks."""
        action = ActionDefinition(
            action_type="resize-ec2",
            resource_type="aws_instance",
            resource_id="i-0abc123def",
            attributes={"instance_type": "t3.medium"},
            import_id="i-0abc123def",
            is_removal=False,
            tags=None,
        )
        doc = action.to_hcl()
        rendered = doc.render()

        assert 'resource "aws_instance"' in rendered
        assert 'instance_type = "t3.medium"' in rendered
        assert "import {" in rendered
        assert 'id = "i-0abc123def"' in rendered

    def test_removal_action_generates_removed_block(self):
        """A removal action generates a removed {} block."""
        action = ActionDefinition(
            action_type="delete-ebs",
            resource_type="aws_ebs_volume",
            resource_id="vol-0abc123",
            attributes={},
            import_id=None,
            is_removal=True,
            tags=None,
        )
        doc = action.to_hcl()
        rendered = doc.render()

        assert "removed {" in rendered
        assert "aws_ebs_volume" in rendered
        assert "lifecycle {" in rendered
        assert "destroy = true" in rendered
        # Should NOT have a resource block
        assert 'resource "aws_ebs_volume"' not in rendered

    def test_action_with_tags(self):
        """Tags are included in the resource block."""
        action = ActionDefinition(
            action_type="apply-tags",
            resource_type="aws_instance",
            resource_id="i-0abc123",
            attributes={},
            import_id="i-0abc123",
            is_removal=False,
            tags={"Name": "my-server", "Environment": "prod"},
        )
        doc = action.to_hcl()
        rendered = doc.render()

        assert "tags = {" in rendered
        assert 'Name = "my-server"' in rendered
        assert 'Environment = "prod"' in rendered

    def test_action_without_import_id(self):
        """An action without import_id doesn't generate an import block."""
        action = ActionDefinition(
            action_type="create-budget",
            resource_type="aws_budgets_budget",
            resource_id="my-budget",
            attributes={"name": "my-budget", "budget_type": "COST"},
            import_id=None,
            is_removal=False,
            tags=None,
        )
        doc = action.to_hcl()
        rendered = doc.render()

        assert 'resource "aws_budgets_budget"' in rendered
        assert "import {" not in rendered


class TestActionDefinitionFromHcl:
    """Tests for ActionDefinition.from_hcl()."""

    def test_parse_resource_action(self):
        """Parse a resource action from HCL document."""
        action = ActionDefinition(
            action_type="resize-ec2",
            resource_type="aws_instance",
            resource_id="i-0abc123def",
            attributes={"instance_type": "t3.medium"},
            import_id="i-0abc123def",
            is_removal=False,
            tags=None,
        )
        doc = action.to_hcl()
        parsed = ActionDefinition.from_hcl(doc)

        assert parsed.action_type == "resize-ec2"
        assert parsed.resource_type == "aws_instance"
        assert parsed.import_id == "i-0abc123def"
        assert parsed.is_removal is False
        assert parsed.attributes["instance_type"] == "t3.medium"

    def test_parse_removal_action(self):
        """Parse a removal action from HCL document."""
        action = ActionDefinition(
            action_type="delete-ebs",
            resource_type="aws_ebs_volume",
            resource_id="vol-0abc123",
            attributes={},
            import_id=None,
            is_removal=True,
            tags=None,
        )
        doc = action.to_hcl()
        parsed = ActionDefinition.from_hcl(doc)

        assert parsed.action_type == "delete-ebs"
        assert parsed.resource_type == "aws_ebs_volume"
        assert parsed.is_removal is True
        assert parsed.import_id is None

    def test_parse_action_with_tags(self):
        """Parse an action with tags from HCL document."""
        action = ActionDefinition(
            action_type="apply-tags",
            resource_type="aws_instance",
            resource_id="i-0abc123",
            attributes={},
            import_id="i-0abc123",
            is_removal=False,
            tags={"Name": "my-server", "Environment": "prod"},
        )
        doc = action.to_hcl()
        parsed = ActionDefinition.from_hcl(doc)

        assert parsed.tags == {"Name": "my-server", "Environment": "prod"}


class TestActionDefinitionRoundTrip:
    """Tests for ActionDefinition round-trip: create -> to_hcl -> render -> parse -> from_hcl -> compare."""

    def test_roundtrip_resize_ec2(self):
        """Round-trip a resize EC2 action."""
        original = ActionDefinition(
            action_type="resize-ec2",
            resource_type="aws_instance",
            resource_id="i-0abc123def",
            attributes={"instance_type": "t3.medium"},
            import_id="i-0abc123def",
            is_removal=False,
            tags=None,
        )
        doc = original.to_hcl()
        rendered = doc.render()
        parsed_doc = HclDocument.parse(rendered)
        result = ActionDefinition.from_hcl(parsed_doc)

        assert result.action_type == original.action_type
        assert result.resource_type == original.resource_type
        assert result.import_id == original.import_id
        assert result.is_removal == original.is_removal
        assert result.attributes == original.attributes
        assert result.tags == original.tags

    def test_roundtrip_delete_ebs(self):
        """Round-trip a delete EBS action."""
        original = ActionDefinition(
            action_type="delete-ebs",
            resource_type="aws_ebs_volume",
            resource_id="vol-0abc123",
            attributes={},
            import_id=None,
            is_removal=True,
            tags=None,
        )
        doc = original.to_hcl()
        rendered = doc.render()
        parsed_doc = HclDocument.parse(rendered)
        result = ActionDefinition.from_hcl(parsed_doc)

        assert result.action_type == original.action_type
        assert result.resource_type == original.resource_type
        assert result.is_removal == original.is_removal
        assert result.import_id == original.import_id

    def test_roundtrip_release_eip(self):
        """Round-trip a release EIP action."""
        original = ActionDefinition(
            action_type="release-eip",
            resource_type="aws_eip",
            resource_id="eipalloc-0abc123",
            attributes={},
            import_id=None,
            is_removal=True,
            tags=None,
        )
        doc = original.to_hcl()
        rendered = doc.render()
        parsed_doc = HclDocument.parse(rendered)
        result = ActionDefinition.from_hcl(parsed_doc)

        assert result.action_type == original.action_type
        assert result.resource_type == original.resource_type
        assert result.is_removal == original.is_removal

    def test_roundtrip_apply_tags(self):
        """Round-trip an apply tags action with tags."""
        original = ActionDefinition(
            action_type="apply-tags",
            resource_type="aws_instance",
            resource_id="i-0abc123",
            attributes={"ami": "ami-12345678"},
            import_id="i-0abc123",
            is_removal=False,
            tags={"Name": "my-server", "Environment": "prod"},
        )
        doc = original.to_hcl()
        rendered = doc.render()
        parsed_doc = HclDocument.parse(rendered)
        result = ActionDefinition.from_hcl(parsed_doc)

        assert result.action_type == original.action_type
        assert result.resource_type == original.resource_type
        assert result.import_id == original.import_id
        assert result.is_removal == original.is_removal
        assert result.attributes == original.attributes
        assert result.tags == original.tags

    def test_roundtrip_create_budget(self):
        """Round-trip a create budget action (no import)."""
        original = ActionDefinition(
            action_type="create-budget",
            resource_type="aws_budgets_budget",
            resource_id="my-budget",
            attributes={"name": "my-budget", "budget_type": "COST", "limit_amount": "100"},
            import_id=None,
            is_removal=False,
            tags=None,
        )
        doc = original.to_hcl()
        rendered = doc.render()
        parsed_doc = HclDocument.parse(rendered)
        result = ActionDefinition.from_hcl(parsed_doc)

        assert result.action_type == original.action_type
        assert result.resource_type == original.resource_type
        assert result.is_removal == original.is_removal
        assert result.attributes == original.attributes

    def test_roundtrip_with_numeric_attributes(self):
        """Round-trip an action with numeric attribute values."""
        original = ActionDefinition(
            action_type="resize-ec2",
            resource_type="aws_instance",
            resource_id="i-0abc123",
            attributes={"instance_type": "t3.medium", "cpu_core_count": 2},
            import_id="i-0abc123",
            is_removal=False,
            tags=None,
        )
        doc = original.to_hcl()
        rendered = doc.render()
        parsed_doc = HclDocument.parse(rendered)
        result = ActionDefinition.from_hcl(parsed_doc)

        assert result.attributes["cpu_core_count"] == 2
        assert result.attributes["instance_type"] == "t3.medium"

    def test_roundtrip_with_boolean_attributes(self):
        """Round-trip an action with boolean attribute values."""
        original = ActionDefinition(
            action_type="resize-ec2",
            resource_type="aws_instance",
            resource_id="i-0abc123",
            attributes={"monitoring": True, "disable_api_termination": False},
            import_id="i-0abc123",
            is_removal=False,
            tags=None,
        )
        doc = original.to_hcl()
        rendered = doc.render()
        parsed_doc = HclDocument.parse(rendered)
        result = ActionDefinition.from_hcl(parsed_doc)

        assert result.attributes["monitoring"] is True
        assert result.attributes["disable_api_termination"] is False
