"""
Connector Configuration Validator.
Validates Connector_Config bodies for the Admin Connector Configuration feature.
Only essential fields are required — technical fields are auto-generated by the frontend.
"""

import re


# Validation patterns
PROVIDER_KEY_PATTERN = re.compile(r'^[a-z][a-z0-9_]{1,30}$')
VALID_AUTH_TYPES = {'iam_role', 'service_principal', 'service_account', 'api_key', 'oauth2'}
VALID_CLOUDS = {'aws', 'azure', 'gcp', 'ai_vendor', 'monitoring', 'other'}

# Only essential fields are required
REQUIRED_FIELDS = [
    'providerKey', 'displayName', 'cloud', 'authType', 'stalenessThresholdHours'
]


def validate_connector_config(body: dict, is_update: bool = False) -> list:
    """Validate a connector config body.

    Collects ALL validation errors and returns them as a list.
    An empty list means the body is valid.

    Only requires essential fields (providerKey, displayName, cloud, authType,
    stalenessThresholdHours). All other fields are optional and auto-generated
    by the frontend.

    Args:
        body: The connector configuration dictionary to validate.
        is_update: If True, skips providerKey requirement (key comes from path).

    Returns:
        List of error message strings. Empty list means valid.
    """
    errors = []

    if not isinstance(body, dict):
        return ['Request body must be a JSON object']

    # Check required fields
    fields_to_check = REQUIRED_FIELDS if not is_update else [f for f in REQUIRED_FIELDS if f != 'providerKey']
    for field in fields_to_check:
        if field not in body or body[field] is None:
            errors.append(f'{field}: is required')

    # Validate providerKey format
    provider_key = body.get('providerKey')
    if provider_key is not None:
        if not isinstance(provider_key, str) or not PROVIDER_KEY_PATTERN.match(provider_key):
            errors.append('providerKey: must match pattern ^[a-z][a-z0-9_]{1,30}$')

    # Validate cloud enum
    cloud = body.get('cloud')
    if cloud is not None:
        if cloud not in VALID_CLOUDS:
            errors.append(f'cloud: must be one of {sorted(VALID_CLOUDS)}')

    # Validate authType enum
    auth_type = body.get('authType')
    if auth_type is not None:
        if auth_type not in VALID_AUTH_TYPES:
            errors.append(f'authType: must be one of {sorted(VALID_AUTH_TYPES)}')

    # Validate stalenessThresholdHours
    staleness = body.get('stalenessThresholdHours')
    if staleness is not None:
        if not isinstance(staleness, int) or staleness < 1 or staleness > 720:
            errors.append('stalenessThresholdHours: must be a positive integer between 1 and 720')

    # --- Optional fields: validate format if present, but don't require ---

    # Validate supportedOperations (optional, but must be valid list if provided)
    supported_ops = body.get('supportedOperations')
    if supported_ops is not None:
        if not isinstance(supported_ops, list) or len(supported_ops) == 0:
            errors.append('supportedOperations: must be a non-empty list of strings')
        elif not all(isinstance(op, str) for op in supported_ops):
            errors.append('supportedOperations: must be a non-empty list of strings')

    # Validate cacheSchema (optional, just check it's a dict if present)
    cache_schema = body.get('cacheSchema')
    if cache_schema is not None:
        if not isinstance(cache_schema, dict):
            errors.append('cacheSchema: must be an object')

    # Validate connectorClass (optional, just check it's a string if present)
    connector_class = body.get('connectorClass')
    if connector_class is not None:
        if not isinstance(connector_class, str) or not connector_class:
            errors.append('connectorClass: must be a non-empty string')

    # Validate invoiceFields (optional, check it's a dict if present)
    invoice_fields = body.get('invoiceFields')
    if invoice_fields is not None:
        if not isinstance(invoice_fields, dict):
            errors.append('invoiceFields: must be an object')

    return errors
