"""Optimization action HCL generators for Terraform code generation.

Dispatches action_type to individual generator functions that produce
valid Terraform HCL for each supported optimization action.

Supported action types:
- resize-ec2: Resize an EC2 instance to a recommended type
- delete-ebs: Delete an unused EBS volume
- release-eip: Release an unused Elastic IP
- s3-lifecycle: Add lifecycle rules to an S3 bucket
- create-schedule: Create start/stop schedules for resources
- apply-tags: Apply recommended tags to a resource
- create-budget: Create a budget with notification thresholds
"""

from __future__ import annotations

from datetime import datetime, timezone

from hcl_generator.core import HclBlock, HclDocument, HclRawExpression, render_provider_block
from hcl_generator.identifiers import to_terraform_identifier


SUPPORTED_ACTION_TYPES: set[str] = {
    "resize-ec2",
    "delete-ebs",
    "release-eip",
    "s3-lifecycle",
    "create-schedule",
    "apply-tags",
    "create-budget",
}


def _build_header_comment(
    action_description: str,
    account_id: str,
    timestamp: datetime | None = None,
) -> str:
    """Build the standard header comment for generated action HCL files.

    Args:
        action_description: Human-readable description of the action.
        account_id: Target AWS account ID.
        timestamp: Generation timestamp. Defaults to current UTC time.

    Returns:
        Multi-line header comment string.
    """
    if timestamp is None:
        timestamp = datetime.now(timezone.utc)

    iso_timestamp = timestamp.strftime("%Y-%m-%dT%H:%M:%SZ")

    lines = [
        "Generated by SlashMyBill - Terraform IaC Integration",
        f"Action: {action_description}",
        f"Account: {account_id}",
        f"Generated: {iso_timestamp}",
        "WARNING: Review this file before applying with terraform apply",
    ]
    return "\n".join(lines)


def _action_description(action_type: str, action_params: dict) -> str:
    """Build a human-readable description for the action header comment.

    Args:
        action_type: The optimization action type.
        action_params: Action-specific parameters.

    Returns:
        A description string for the header comment.
    """
    descriptions = {
        "resize-ec2": lambda p: (
            f"Resize EC2 instance {p.get('instanceId', 'unknown')} "
            f"to {p.get('targetInstanceType', 'unknown')}"
        ),
        "delete-ebs": lambda p: (
            f"Delete EBS volume {p.get('volumeId', 'unknown')}"
        ),
        "release-eip": lambda p: (
            f"Release Elastic IP {p.get('allocationId', 'unknown')}"
        ),
        "s3-lifecycle": lambda p: (
            f"Add lifecycle rules to S3 bucket {p.get('bucketName', 'unknown')}"
        ),
        "create-schedule": lambda p: (
            f"Create start/stop schedule for {p.get('resourceType', 'resource')} "
            f"{p.get('resourceId', 'unknown')}"
        ),
        "apply-tags": lambda p: (
            f"Apply tags to {p.get('resourceType', 'resource')} "
            f"{p.get('resourceId', 'unknown')}"
        ),
        "create-budget": lambda p: (
            f"Create budget {p.get('budgetName', 'unknown')}"
        ),
    }
    desc_fn = descriptions.get(action_type)
    if desc_fn:
        return desc_fn(action_params)
    return f"Optimization action: {action_type}"


def generate_action_hcl(
    action_type: str,
    action_params: dict,
    account_id: str,
    region: str = "us-east-1",
) -> HclDocument:
    """Generate Terraform HCL for an optimization action.

    Validates the action type, builds a header comment, and dispatches
    to the appropriate generator function.

    Args:
        action_type: The optimization action type (must be in SUPPORTED_ACTION_TYPES).
        action_params: Action-specific parameters dict.
        account_id: Target AWS account ID (12 digits).
        region: AWS region (defaults to us-east-1).

    Returns:
        An HclDocument containing the generated Terraform configuration.

    Raises:
        ValueError: If action_type is not in SUPPORTED_ACTION_TYPES.
    """
    if action_type not in SUPPORTED_ACTION_TYPES:
        raise ValueError(
            f"Unsupported action type: '{action_type}'. "
            f"Supported types are: {sorted(SUPPORTED_ACTION_TYPES)}"
        )

    # Build header comment
    description = _action_description(action_type, action_params)
    header = _build_header_comment(description, account_id)

    # Dispatch table mapping action types to generator functions
    dispatch: dict[str, callable] = {
        "resize-ec2": _generate_resize_ec2,
        "delete-ebs": _generate_delete_ebs,
        "release-eip": _generate_release_eip,
        "s3-lifecycle": _generate_s3_lifecycle,
        "create-schedule": _generate_create_schedule,
        "apply-tags": _generate_apply_tags,
        "create-budget": _generate_create_budget,
    }

    generator_fn = dispatch[action_type]
    return generator_fn(action_params, account_id, region, header)


def _generate_resize_ec2(
    action_params: dict, account_id: str, region: str, header: str
) -> HclDocument:
    """Generate HCL for resizing an EC2 instance.

    Args:
        action_params: Must contain 'instanceId' and 'targetInstanceType'.
        account_id: Target AWS account ID.
        region: AWS region.
        header: Pre-built header comment string.

    Returns:
        HclDocument with the resize EC2 configuration.
    """
    instance_id = action_params.get("instanceId", "")
    target_instance_type = action_params.get("targetInstanceType", "")

    resource_name = to_terraform_identifier(instance_id) if instance_id else "instance"

    # terraform { required_providers {} } block
    aws_provider_source = HclBlock(
        block_type="aws",
        labels=[],
        attributes={
            "source": "hashicorp/aws",
            "version": ">= 5.0",
        },
    )
    required_providers_block = HclBlock(
        block_type="required_providers",
        labels=[],
        nested_blocks=[aws_provider_source],
    )
    terraform_block = HclBlock(
        block_type="terraform",
        labels=[],
        nested_blocks=[required_providers_block],
    )

    # provider "aws" block with assume_role
    provider_block = render_provider_block(region, account_id)

    # aws_instance resource block
    resource_block = HclBlock(
        block_type="resource",
        labels=["aws_instance", resource_name],
        attributes={
            "instance_type": target_instance_type,
        },
    )

    # import {} block
    import_block = HclBlock(
        block_type="import",
        labels=[],
        attributes={
            "to": HclRawExpression(f"aws_instance.{resource_name}"),
            "id": instance_id,
        },
    )

    doc = HclDocument(
        blocks=[terraform_block, provider_block, resource_block, import_block],
        header_comment=header,
    )
    return doc


def _generate_delete_ebs(
    action_params: dict, account_id: str, region: str, header: str
) -> HclDocument:
    """Generate HCL for deleting an EBS volume using a removed {} block.

    Uses Terraform 1.7+ removed {} block syntax to destroy the volume
    without requiring it to be in state first.

    Args:
        action_params: Must contain 'volumeId'.
        account_id: Target AWS account ID.
        region: AWS region.
        header: Pre-built header comment string.

    Returns:
        HclDocument with the delete EBS configuration.
    """
    volume_id = action_params.get("volumeId", "unknown")
    tf_name = to_terraform_identifier(volume_id)

    # terraform { required_providers {} } block
    aws_provider_source = HclBlock(
        block_type="aws",
        labels=[],
        attributes={
            "source": "hashicorp/aws",
            "version": ">= 5.0",
        },
    )
    required_providers = HclBlock(
        block_type="required_providers",
        labels=[],
        nested_blocks=[aws_provider_source],
    )
    terraform_block = HclBlock(
        block_type="terraform",
        labels=[],
        nested_blocks=[required_providers],
    )

    # provider "aws" block
    provider_block = render_provider_block(region, account_id)

    # removed {} block with lifecycle { destroy = true }
    lifecycle_block = HclBlock(
        block_type="lifecycle",
        labels=[],
        attributes={"destroy": True},
    )
    removed_block = HclBlock(
        block_type="removed",
        labels=[],
        attributes={
            "from": HclRawExpression(f"aws_ebs_volume.{tf_name}"),
        },
        nested_blocks=[lifecycle_block],
    )

    return HclDocument(
        blocks=[terraform_block, provider_block, removed_block],
        header_comment=header,
    )


def _generate_release_eip(
    action_params: dict, account_id: str, region: str, header: str
) -> HclDocument:
    """Generate HCL for releasing an Elastic IP using a removed {} block.

    Uses Terraform 1.7+ removed {} block syntax to release the EIP
    without requiring it to be in state first.

    Args:
        action_params: Must contain 'allocationId'.
        account_id: Target AWS account ID.
        region: AWS region.
        header: Pre-built header comment string.

    Returns:
        HclDocument with the release EIP configuration.
    """
    allocation_id = action_params.get("allocationId", "unknown")
    tf_name = to_terraform_identifier(allocation_id)

    # terraform { required_providers {} } block
    aws_provider_source = HclBlock(
        block_type="aws",
        labels=[],
        attributes={
            "source": "hashicorp/aws",
            "version": ">= 5.0",
        },
    )
    required_providers = HclBlock(
        block_type="required_providers",
        labels=[],
        nested_blocks=[aws_provider_source],
    )
    terraform_block = HclBlock(
        block_type="terraform",
        labels=[],
        nested_blocks=[required_providers],
    )

    # provider "aws" block
    provider_block = render_provider_block(region, account_id)

    # removed {} block with lifecycle { destroy = true }
    lifecycle_block = HclBlock(
        block_type="lifecycle",
        labels=[],
        attributes={"destroy": True},
    )
    removed_block = HclBlock(
        block_type="removed",
        labels=[],
        attributes={
            "from": HclRawExpression(f"aws_eip.{tf_name}"),
        },
        nested_blocks=[lifecycle_block],
    )

    return HclDocument(
        blocks=[terraform_block, provider_block, removed_block],
        header_comment=header,
    )


def _generate_s3_lifecycle(
    action_params: dict, account_id: str, region: str, header: str
) -> HclDocument:
    """Generate HCL for adding S3 lifecycle rules.

    Args:
        action_params: Must contain 'bucketName', 'transitionDays',
            'storageClass', and 'expirationDays'.
        account_id: Target AWS account ID.
        region: AWS region.
        header: Pre-built header comment string.

    Returns:
        HclDocument with the S3 lifecycle configuration.
    """
    bucket_name = action_params.get("bucketName", "unknown-bucket")
    transition_days = action_params.get("transitionDays", 30)
    storage_class = action_params.get("storageClass", "GLACIER")
    expiration_days = action_params.get("expirationDays", 365)

    resource_name = to_terraform_identifier(bucket_name)

    # terraform { required_providers {} } block
    aws_provider_source = HclBlock(
        block_type="aws",
        labels=[],
        attributes={
            "source": "hashicorp/aws",
            "version": ">= 5.0",
        },
    )
    required_providers_block = HclBlock(
        block_type="required_providers",
        labels=[],
        nested_blocks=[aws_provider_source],
    )
    terraform_block = HclBlock(
        block_type="terraform",
        labels=[],
        nested_blocks=[required_providers_block],
    )

    # provider "aws" block
    provider_block = render_provider_block(region, account_id)

    # Transition nested block
    transition_block = HclBlock(
        block_type="transition",
        labels=[],
        attributes={
            "days": transition_days,
            "storage_class": storage_class,
        },
    )

    # Expiration nested block
    expiration_block = HclBlock(
        block_type="expiration",
        labels=[],
        attributes={
            "days": expiration_days,
        },
    )

    # Rule nested block
    rule_block = HclBlock(
        block_type="rule",
        labels=[],
        attributes={
            "id": "slashmybill-lifecycle-rule",
            "status": "Enabled",
        },
        nested_blocks=[transition_block, expiration_block],
    )

    # aws_s3_bucket_lifecycle_configuration resource
    lifecycle_resource = HclBlock(
        block_type="resource",
        labels=["aws_s3_bucket_lifecycle_configuration", resource_name],
        attributes={
            "bucket": bucket_name,
        },
        nested_blocks=[rule_block],
    )

    # import {} block
    import_block = HclBlock(
        block_type="import",
        labels=[],
        attributes={
            "to": HclRawExpression(
                f"aws_s3_bucket_lifecycle_configuration.{resource_name}"
            ),
            "id": bucket_name,
        },
    )

    return HclDocument(
        blocks=[terraform_block, provider_block, lifecycle_resource, import_block],
        header_comment=header,
    )


def _generate_create_schedule(
    action_params: dict, account_id: str, region: str, header: str
) -> HclDocument:
    """Generate HCL for creating start/stop schedules.

    Args:
        action_params: Must contain 'resourceId', 'resourceType',
            'startCron', 'stopCron', and 'timezone'.
        account_id: Target AWS account ID.
        region: AWS region.
        header: Pre-built header comment string.

    Returns:
        HclDocument with the schedule configuration.
    """
    resource_id = action_params.get("resourceId", "unknown")
    resource_type = action_params.get("resourceType", "resource")
    start_cron = action_params.get("startCron", "0 8 * * *")
    stop_cron = action_params.get("stopCron", "0 18 * * *")
    tz = action_params.get("timezone", "UTC")

    tf_id = to_terraform_identifier(resource_id)

    # terraform { required_providers {} } block
    aws_provider_source = HclBlock(
        block_type="aws",
        labels=[],
        attributes={
            "source": "hashicorp/aws",
            "version": ">= 5.0",
        },
    )
    required_providers_block = HclBlock(
        block_type="required_providers",
        labels=[],
        nested_blocks=[aws_provider_source],
    )
    terraform_block = HclBlock(
        block_type="terraform",
        labels=[],
        nested_blocks=[required_providers_block],
    )

    # provider "aws" block
    provider_block = render_provider_block(region, account_id)

    # Start schedule resource
    start_flexible_window = HclBlock(
        block_type="flexible_time_window",
        labels=[],
        attributes={"mode": "OFF"},
    )
    start_target = HclBlock(
        block_type="target",
        labels=[],
        attributes={
            "arn": f"# TODO: Set target ARN for {resource_type} {resource_id}",
            "role_arn": f"# TODO: Set execution role ARN",
        },
    )
    start_schedule = HclBlock(
        block_type="resource",
        labels=["aws_scheduler_schedule", f"start_{tf_id}"],
        attributes={
            "name": f"slashmybill-start-{resource_id}",
            "schedule_expression": f"cron({start_cron})",
            "schedule_expression_timezone": tz,
        },
        nested_blocks=[start_flexible_window, start_target],
    )

    # Stop schedule resource
    stop_flexible_window = HclBlock(
        block_type="flexible_time_window",
        labels=[],
        attributes={"mode": "OFF"},
    )
    stop_target = HclBlock(
        block_type="target",
        labels=[],
        attributes={
            "arn": f"# TODO: Set target ARN for {resource_type} {resource_id}",
            "role_arn": f"# TODO: Set execution role ARN",
        },
    )
    stop_schedule = HclBlock(
        block_type="resource",
        labels=["aws_scheduler_schedule", f"stop_{tf_id}"],
        attributes={
            "name": f"slashmybill-stop-{resource_id}",
            "schedule_expression": f"cron({stop_cron})",
            "schedule_expression_timezone": tz,
        },
        nested_blocks=[stop_flexible_window, stop_target],
    )

    return HclDocument(
        blocks=[terraform_block, provider_block, start_schedule, stop_schedule],
        header_comment=header,
    )


def _generate_apply_tags(
    action_params: dict, account_id: str, region: str, header: str
) -> HclDocument:
    """Generate HCL for applying tags to a resource.

    Creates the target resource with the recommended tags and an import block
    to adopt the existing resource into Terraform state.

    Args:
        action_params: Must contain 'resourceId', 'resourceType', and 'tags'.
        account_id: Target AWS account ID.
        region: AWS region.
        header: Pre-built header comment string.

    Returns:
        HclDocument with the apply tags configuration.
    """
    resource_id = action_params.get("resourceId", "")
    resource_type = action_params.get("resourceType", "")
    tags = action_params.get("tags", {})

    # Map resourceType to Terraform resource type
    resource_type_map = {
        "ec2": "aws_instance",
        "ebs": "aws_ebs_volume",
        "s3": "aws_s3_bucket",
        "eip": "aws_eip",
        "rds": "aws_db_instance",
        "lambda": "aws_lambda_function",
        "elb": "aws_lb",
    }
    tf_resource_type = resource_type_map.get(resource_type, f"aws_{resource_type}")

    # Create a valid Terraform identifier from the resource ID
    tf_name = to_terraform_identifier(resource_id)

    # terraform { required_providers {} } block
    aws_provider_block = HclBlock(
        block_type="aws",
        labels=[],
        attributes={
            "source": "hashicorp/aws",
            "version": ">= 5.0",
        },
    )
    required_providers_block = HclBlock(
        block_type="required_providers",
        labels=[],
        nested_blocks=[aws_provider_block],
    )
    terraform_block = HclBlock(
        block_type="terraform",
        labels=[],
        nested_blocks=[required_providers_block],
    )

    # provider "aws" block
    provider_block = render_provider_block(region, account_id)

    # Target resource with tags
    resource_block = HclBlock(
        block_type="resource",
        labels=[tf_resource_type, tf_name],
        attributes={
            "tags": tags,
        },
    )

    # import {} block
    import_block = HclBlock(
        block_type="import",
        labels=[],
        attributes={
            "to": HclRawExpression(f"{tf_resource_type}.{tf_name}"),
            "id": resource_id,
        },
    )

    return HclDocument(
        blocks=[terraform_block, provider_block, resource_block, import_block],
        header_comment=header,
    )


def _generate_create_budget(
    action_params: dict, account_id: str, region: str, header: str
) -> HclDocument:
    """Generate HCL for creating a budget.

    Creates an aws_budgets_budget resource with the specified amount, time period,
    and notification thresholds for each threshold value.

    Args:
        action_params: Must contain 'budgetName', 'amount', 'timeUnit',
            'notificationThresholds', and 'subscriberEmail'.
        account_id: Target AWS account ID.
        region: AWS region.
        header: Pre-built header comment string.

    Returns:
        HclDocument with the budget configuration.
    """
    budget_name = action_params.get("budgetName", "slashmybill-budget")
    amount = action_params.get("amount", 0)
    time_unit = action_params.get("timeUnit", "MONTHLY")
    notification_thresholds = action_params.get("notificationThresholds", [80, 100])
    subscriber_email = action_params.get("subscriberEmail", "")

    # Create a valid Terraform identifier from the budget name
    tf_name = to_terraform_identifier(budget_name)

    # terraform { required_providers {} } block
    aws_provider_block = HclBlock(
        block_type="aws",
        labels=[],
        attributes={
            "source": "hashicorp/aws",
            "version": ">= 5.0",
        },
    )
    required_providers_block = HclBlock(
        block_type="required_providers",
        labels=[],
        nested_blocks=[aws_provider_block],
    )
    terraform_block = HclBlock(
        block_type="terraform",
        labels=[],
        nested_blocks=[required_providers_block],
    )

    # provider "aws" block
    provider_block = render_provider_block(region, account_id)

    # Build notification nested blocks
    notification_blocks = []
    for threshold in notification_thresholds:
        notification_block = HclBlock(
            block_type="notification",
            labels=[],
            attributes={
                "comparison_operator": "GREATER_THAN",
                "threshold": threshold,
                "threshold_type": "PERCENTAGE",
                "notification_type": "ACTUAL",
                "subscriber_email_addresses": [subscriber_email],
            },
        )
        notification_blocks.append(notification_block)

    # aws_budgets_budget resource
    budget_block = HclBlock(
        block_type="resource",
        labels=["aws_budgets_budget", tf_name],
        attributes={
            "name": budget_name,
            "budget_type": "COST",
            "limit_amount": str(amount),
            "limit_unit": "USD",
            "time_unit": time_unit,
        },
        nested_blocks=notification_blocks,
    )

    return HclDocument(
        blocks=[terraform_block, provider_block, budget_block],
        header_comment=header,
    )
