"""RI/SP commitment snippet generator for Terraform code generation.

Generates commented HCL documenting commitment details (type, term, payment
option, savings, instance family) and an active aws_budgets_budget resource
for tracking commitment spend with notification rules.

RI/SP purchases cannot be made via Terraform — the generated snippet documents
the commitment decision and creates a budget for tracking and alerting.
"""

from __future__ import annotations

from hcl_generator.core import HclBlock, HclDocument, render_provider_block


def _build_commitment_header(
    commitment_type: str,
    options: list[dict],
    account_id: str,
) -> str:
    """Build the header comment for a commitment snippet.

    Includes:
    - A title explaining this is a commitment documentation snippet
    - A note that RI/SP must be purchased via AWS Console/CLI
    - Separate commented sections for each option

    Args:
        commitment_type: "ri" or "sp".
        options: List of commitment option dicts.
        account_id: Target AWS account ID.

    Returns:
        Multi-line header comment string.
    """
    type_label = "Reserved Instance" if commitment_type == "ri" else "Savings Plan"

    lines = [
        f"Generated by SlashMyBill - {type_label} Commitment Documentation",
        f"Account: {account_id}",
        "",
        "IMPORTANT: Reserved Instances and Savings Plans cannot be purchased via Terraform.",
        "They must be purchased through the AWS Console or AWS CLI.",
        "The budget resource below serves as a tracking and alerting mechanism",
        "for your commitment spend.",
        "",
    ]

    # Generate separate commented sections for each option
    for i, option in enumerate(options, start=1):
        term = option.get("term", "unknown")
        payment_option = option.get("paymentOption", "unknown")
        estimated_savings = option.get("estimatedSavings", 0)
        instance_family = option.get("instanceFamily", "")
        compute_type = option.get("computeType", "")
        monthly_commitment = option.get("monthlyCommitment", 0)

        lines.append(f"--- Option {i}: {term}, {payment_option} ---")
        lines.append(f"  Type: {type_label}")
        lines.append(f"  Term: {term}")
        lines.append(f"  Payment Option: {payment_option}")
        lines.append(f"  Estimated Savings: ${estimated_savings}/month")

        if instance_family:
            lines.append(f"  Instance Family: {instance_family}")
        if compute_type:
            lines.append(f"  Compute Type: {compute_type}")

        lines.append(f"  Monthly Commitment: ${monthly_commitment}")
        lines.append("")

    return "\n".join(lines)


def generate_commitment_snippet(
    commitment_type: str,
    options: list[dict],
    member_email: str,
    account_id: str,
) -> HclDocument:
    """Generate a commitment documentation snippet with budget tracking.

    Produces an HclDocument containing:
    1. A header comment documenting the commitment details and options
    2. A note that RI/SP must be purchased via AWS Console/CLI
    3. Separate commented sections for each option
    4. An active aws_budgets_budget resource using the first option's
       monthlyCommitment as the budget limit, with notification rules
       at 80% and 100% thresholds

    Args:
        commitment_type: "ri" or "sp".
        options: List of commitment option dicts. Each option should contain:
            - term: "1-year" or "3-year"
            - paymentOption: "all-upfront", "partial-upfront", or "no-upfront"
            - estimatedSavings: Estimated monthly savings amount
            - instanceFamily: Instance family (e.g., "m5", "c5") - for RI
            - computeType: Compute type (e.g., "EC2", "Fargate") - for SP
            - monthlyCommitment: Monthly commitment amount in USD
        member_email: Member email for budget notification subscriber.
        account_id: Target AWS account ID.

    Returns:
        An HclDocument with the commitment snippet.
    """
    # Build header comment with all option documentation
    header = _build_commitment_header(commitment_type, options, account_id)

    # Use the first option's monthlyCommitment as the budget limit
    first_option = options[0] if options else {}
    monthly_commitment = first_option.get("monthlyCommitment", 0)

    # terraform { required_providers {} } block
    aws_provider_source = HclBlock(
        block_type="aws",
        labels=[],
        attributes={
            "source": "hashicorp/aws",
            "version": ">= 5.0",
        },
    )
    required_providers_block = HclBlock(
        block_type="required_providers",
        labels=[],
        nested_blocks=[aws_provider_source],
    )
    terraform_block = HclBlock(
        block_type="terraform",
        labels=[],
        nested_blocks=[required_providers_block],
    )

    # provider "aws" block with assume_role
    provider_block = render_provider_block("us-east-1", account_id)

    # Build notification nested blocks at 80% and 100%
    notification_80 = HclBlock(
        block_type="notification",
        labels=[],
        attributes={
            "comparison_operator": "GREATER_THAN",
            "threshold": 80,
            "threshold_type": "PERCENTAGE",
            "notification_type": "ACTUAL",
            "subscriber_email_addresses": [member_email],
        },
    )
    notification_100 = HclBlock(
        block_type="notification",
        labels=[],
        attributes={
            "comparison_operator": "GREATER_THAN",
            "threshold": 100,
            "threshold_type": "PERCENTAGE",
            "notification_type": "ACTUAL",
            "subscriber_email_addresses": [member_email],
        },
    )

    # Determine budget resource name
    type_suffix = "ri" if commitment_type == "ri" else "sp"
    budget_name = f"slashmybill-{type_suffix}-commitment-tracking"

    # aws_budgets_budget resource
    budget_block = HclBlock(
        block_type="resource",
        labels=["aws_budgets_budget", f"{type_suffix}_commitment_tracking"],
        attributes={
            "name": budget_name,
            "budget_type": "COST",
            "limit_amount": str(monthly_commitment),
            "limit_unit": "USD",
            "time_unit": "MONTHLY",
        },
        nested_blocks=[notification_80, notification_100],
    )

    return HclDocument(
        blocks=[terraform_block, provider_block, budget_block],
        header_comment=header,
    )
