"""Action definition model for round-trip HCL verification.

Provides the ActionDefinition dataclass that represents a structured
optimization action, with methods to serialize to HCL and parse back
from HCL for round-trip testing.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any

from hcl_generator.core import (
    HclBlock,
    HclDocument,
    HclRawExpression,
    render_provider_block,
)
from hcl_generator.identifiers import to_terraform_identifier


@dataclass
class ActionDefinition:
    """Structured representation of an optimization action for round-trip testing.

    Attributes:
        action_type: The optimization action type (e.g., "resize-ec2", "delete-ebs").
        resource_type: AWS Terraform resource type (e.g., "aws_instance", "aws_ebs_volume").
        resource_id: AWS resource identifier (e.g., "i-0abc123def").
        attributes: Resource attributes to set in the HCL block.
        import_id: AWS ID for the import block (None for removed blocks).
        is_removal: True for delete/release actions using removed {} block.
        tags: Optional tags dict.
    """

    action_type: str
    resource_type: str
    resource_id: str
    attributes: dict = field(default_factory=dict)
    import_id: str | None = None
    is_removal: bool = False
    tags: dict | None = None

    def to_hcl(self) -> HclDocument:
        """Serialize this ActionDefinition to an HclDocument.

        Generates a complete Terraform configuration file with:
        - A header comment describing the action
        - A terraform { required_providers {} } block
        - A provider "aws" block (using a placeholder account/region)
        - Either a resource block with import, or a removed block

        Returns:
            An HclDocument representing this action definition.
        """
        # Build header comment
        header = (
            f"Generated by SlashMyBill - Terraform IaC Integration\n"
            f"Action: {self.action_type} for {self.resource_id}\n"
            f"Account: 000000000000\n"
            f"Generated: 2024-01-01T00:00:00Z\n"
            f"WARNING: Review this file before applying with terraform apply"
        )

        # terraform { required_providers { aws {} } }
        aws_provider_source = HclBlock(
            block_type="aws",
            labels=[],
            attributes={
                "source": "hashicorp/aws",
                "version": ">= 5.0",
            },
        )
        required_providers_block = HclBlock(
            block_type="required_providers",
            labels=[],
            nested_blocks=[aws_provider_source],
        )
        terraform_block = HclBlock(
            block_type="terraform",
            labels=[],
            nested_blocks=[required_providers_block],
        )

        # provider "aws" block
        provider_block = render_provider_block("us-east-1", "000000000000")

        blocks = [terraform_block, provider_block]

        tf_name = to_terraform_identifier(self.resource_id)

        if self.is_removal:
            # Generate a removed {} block
            lifecycle_block = HclBlock(
                block_type="lifecycle",
                labels=[],
                attributes={"destroy": True},
            )
            removed_block = HclBlock(
                block_type="removed",
                labels=[],
                attributes={
                    "from": HclRawExpression(f"{self.resource_type}.{tf_name}"),
                },
                nested_blocks=[lifecycle_block],
            )
            blocks.append(removed_block)
        else:
            # Generate a resource block
            resource_attrs = dict(self.attributes)
            if self.tags:
                resource_attrs["tags"] = self.tags

            resource_block = HclBlock(
                block_type="resource",
                labels=[self.resource_type, tf_name],
                attributes=resource_attrs,
            )
            blocks.append(resource_block)

            # Generate import block if import_id is provided
            if self.import_id is not None:
                import_block = HclBlock(
                    block_type="import",
                    labels=[],
                    attributes={
                        "to": HclRawExpression(f"{self.resource_type}.{tf_name}"),
                        "id": self.import_id,
                    },
                )
                blocks.append(import_block)

        return HclDocument(blocks=blocks, header_comment=header)

    @classmethod
    def from_hcl(cls, doc: HclDocument) -> "ActionDefinition":
        """Parse an HclDocument back into an ActionDefinition.

        Reconstructs the action definition by:
        - Finding the resource block or removed block
        - Extracting the resource type and name
        - Extracting attributes
        - Finding the import block (if present) to get import_id
        - Determining if it's a removal (removed {} block present)

        Args:
            doc: An HclDocument to parse.

        Returns:
            An ActionDefinition reconstructed from the document.

        Raises:
            ValueError: If the document doesn't contain a recognizable action.
        """
        resource_type = ""
        resource_id = ""
        attributes: dict = {}
        import_id: str | None = None
        is_removal = False
        tags: dict | None = None
        action_type = ""

        # Extract action_type from header comment
        if doc.header_comment:
            for line in doc.header_comment.splitlines():
                if line.startswith("Action: "):
                    action_part = line[len("Action: "):]
                    # Format: "action_type for resource_id"
                    if " for " in action_part:
                        action_type = action_part.split(" for ")[0].strip()
                    else:
                        action_type = action_part.strip()
                    break

        # Look for resource blocks and removed blocks
        for block in doc.blocks:
            if block.block_type == "resource" and len(block.labels) == 2:
                resource_type = block.labels[0]
                tf_name = block.labels[1]
                # Extract attributes (excluding tags which are handled separately)
                for key, value in block.attributes.items():
                    if key == "tags" and isinstance(value, dict):
                        tags = value
                    else:
                        attributes[key] = value

            elif block.block_type == "removed":
                is_removal = True
                # Extract resource type from the "from" attribute
                from_attr = block.attributes.get("from")
                if isinstance(from_attr, HclRawExpression):
                    # Format: "aws_ebs_volume.tf_name"
                    parts = from_attr.expression.split(".", 1)
                    if len(parts) == 2:
                        resource_type = parts[0]
                        tf_name = parts[1]

            elif block.block_type == "import":
                # Extract import_id from the "id" attribute
                id_attr = block.attributes.get("id")
                if isinstance(id_attr, str):
                    import_id = id_attr
                    resource_id = id_attr

        # If we found a resource block but no import, derive resource_id from tf_name
        if not resource_id and not is_removal:
            # The resource_id is the import_id if available, otherwise
            # we try to reverse the terraform identifier
            if import_id:
                resource_id = import_id

        # For removal actions, derive resource_id from the "from" expression
        if is_removal and not resource_id:
            for block in doc.blocks:
                if block.block_type == "removed":
                    from_attr = block.attributes.get("from")
                    if isinstance(from_attr, HclRawExpression):
                        parts = from_attr.expression.split(".", 1)
                        if len(parts) == 2:
                            # tf_name is the identifier - use it as resource_id
                            resource_id = parts[1]

        return cls(
            action_type=action_type,
            resource_type=resource_type,
            resource_id=resource_id,
            attributes=attributes,
            import_id=import_id,
            is_removal=is_removal,
            tags=tags if tags else None,
        )
