"""Waste action HCL generators with import-then-destroy workflow.

Generates Terraform HCL for waste actions that use the import-then-destroy
pattern: first import the existing resource into Terraform state, then
remove the resource block and re-apply to destroy it.

Supported waste types:
- ebs-volume: Delete an unused EBS volume
- elastic-ip: Release an unused Elastic IP
- load-balancer: Delete an idle load balancer (ALB, NLB, or Classic)
"""

from __future__ import annotations

from datetime import datetime, timezone

from hcl_generator.core import HclBlock, HclDocument, HclRawExpression, render_provider_block
from hcl_generator.identifiers import to_terraform_identifier


SUPPORTED_WASTE_TYPES: set[str] = {
    "ebs-volume",
    "elastic-ip",
    "load-balancer",
}

# Step-by-step workflow comment explaining the import-then-destroy process
_WORKFLOW_COMMENT = """\
Import-then-Destroy Workflow:
1. terraform init
2. terraform plan - verify the import will succeed
3. terraform apply - import the resource into state
4. Remove the resource block from this file
5. terraform apply - destroy the resource"""


def _build_header_comment(
    action_description: str,
    account_id: str,
    timestamp: datetime | None = None,
) -> str:
    """Build the standard header comment for generated waste action HCL files.

    Includes the workflow comment explaining the import-then-destroy process.

    Args:
        action_description: Human-readable description of the waste action.
        account_id: Target AWS account ID.
        timestamp: Generation timestamp. Defaults to current UTC time.

    Returns:
        Multi-line header comment string including workflow instructions.
    """
    if timestamp is None:
        timestamp = datetime.now(timezone.utc)

    iso_timestamp = timestamp.strftime("%Y-%m-%dT%H:%M:%SZ")

    lines = [
        "Generated by SlashMyBill - Terraform IaC Integration",
        f"Action: {action_description}",
        f"Account: {account_id}",
        f"Generated: {iso_timestamp}",
        "WARNING: Review this file before applying with terraform apply",
        "",
        _WORKFLOW_COMMENT,
    ]
    return "\n".join(lines)


def _waste_action_description(waste_type: str, resource_attributes: dict) -> str:
    """Build a human-readable description for the waste action header comment.

    Args:
        waste_type: The waste action type.
        resource_attributes: Resource attributes dict.

    Returns:
        A description string for the header comment.
    """
    descriptions = {
        "ebs-volume": lambda attrs: (
            f"Delete EBS volume {attrs.get('volume_id', 'unknown')}"
        ),
        "elastic-ip": lambda attrs: (
            f"Release Elastic IP {attrs.get('allocation_id', 'unknown')} "
            f"({attrs.get('public_ip', 'unknown')})"
        ),
        "load-balancer": lambda attrs: (
            f"Delete load balancer {attrs.get('name', attrs.get('arn', 'unknown'))}"
        ),
    }
    desc_fn = descriptions.get(waste_type)
    if desc_fn:
        return desc_fn(resource_attributes)
    return f"Waste action: {waste_type}"


def generate_waste_action_hcl(
    waste_type: str,
    resource_attributes: dict,
    account_id: str,
    region: str = "us-east-1",
) -> HclDocument:
    """Generate import-then-destroy workflow HCL for a waste action.

    Produces a Terraform configuration containing:
    1. A resource definition with all current attributes
    2. An import {} block to bring the resource under Terraform management
    3. A step-by-step workflow comment explaining the import-then-destroy process

    Args:
        waste_type: The waste action type ("ebs-volume", "elastic-ip", "load-balancer").
        resource_attributes: Current attributes from AWS API for the resource.
        account_id: Target AWS account ID (12 digits).
        region: AWS region (defaults to us-east-1).

    Returns:
        An HclDocument containing the generated Terraform configuration.

    Raises:
        ValueError: If waste_type is not in SUPPORTED_WASTE_TYPES.
    """
    if waste_type not in SUPPORTED_WASTE_TYPES:
        raise ValueError(
            f"Unsupported waste type: '{waste_type}'. "
            f"Supported types are: {sorted(SUPPORTED_WASTE_TYPES)}"
        )

    # Build header comment with workflow instructions
    description = _waste_action_description(waste_type, resource_attributes)
    header = _build_header_comment(description, account_id)

    # Dispatch to the appropriate generator
    dispatch: dict[str, callable] = {
        "ebs-volume": _generate_ebs_volume_waste,
        "elastic-ip": _generate_eip_waste,
        "load-balancer": _generate_load_balancer_waste,
    }

    generator_fn = dispatch[waste_type]
    return generator_fn(resource_attributes, account_id, region, header)


def _build_terraform_and_provider_blocks(
    region: str, account_id: str
) -> tuple[HclBlock, HclBlock]:
    """Build the standard terraform {} and provider blocks.

    Args:
        region: AWS region.
        account_id: Target AWS account ID.

    Returns:
        Tuple of (terraform_block, provider_block).
    """
    aws_provider_source = HclBlock(
        block_type="aws",
        labels=[],
        attributes={
            "source": "hashicorp/aws",
            "version": ">= 5.0",
        },
    )
    required_providers_block = HclBlock(
        block_type="required_providers",
        labels=[],
        nested_blocks=[aws_provider_source],
    )
    terraform_block = HclBlock(
        block_type="terraform",
        labels=[],
        nested_blocks=[required_providers_block],
    )

    provider_block = render_provider_block(region, account_id)

    return terraform_block, provider_block


def _generate_ebs_volume_waste(
    resource_attributes: dict, account_id: str, region: str, header: str
) -> HclDocument:
    """Generate HCL for deleting an EBS volume via import-then-destroy.

    Creates an aws_ebs_volume resource with all current attributes and an
    import {} block to bring it under Terraform management.

    Args:
        resource_attributes: Must contain 'volume_id', 'size', 'volume_type',
            'availability_zone'. May contain 'tags', 'iops', 'throughput'.
        account_id: Target AWS account ID.
        region: AWS region.
        header: Pre-built header comment string.

    Returns:
        HclDocument with the EBS volume waste action configuration.
    """
    volume_id = resource_attributes.get("volume_id", "unknown")
    size = resource_attributes.get("size", 8)
    volume_type = resource_attributes.get("volume_type", "gp2")
    availability_zone = resource_attributes.get("availability_zone", "")
    tags = resource_attributes.get("tags", {})
    iops = resource_attributes.get("iops")
    throughput = resource_attributes.get("throughput")

    tf_name = to_terraform_identifier(volume_id)

    terraform_block, provider_block = _build_terraform_and_provider_blocks(region, account_id)

    # Build resource attributes
    attrs: dict = {
        "availability_zone": availability_zone,
        "size": size,
        "type": volume_type,
    }

    # Add optional attributes if present
    if iops is not None:
        attrs["iops"] = iops
    if throughput is not None:
        attrs["throughput"] = throughput
    if tags:
        attrs["tags"] = tags

    # aws_ebs_volume resource block
    resource_block = HclBlock(
        block_type="resource",
        labels=["aws_ebs_volume", tf_name],
        attributes=attrs,
    )

    # import {} block
    import_block = HclBlock(
        block_type="import",
        labels=[],
        attributes={
            "to": HclRawExpression(f"aws_ebs_volume.{tf_name}"),
            "id": volume_id,
        },
    )

    return HclDocument(
        blocks=[terraform_block, provider_block, resource_block, import_block],
        header_comment=header,
    )


def _generate_eip_waste(
    resource_attributes: dict, account_id: str, region: str, header: str
) -> HclDocument:
    """Generate HCL for releasing an Elastic IP via import-then-destroy.

    Creates an aws_eip resource with current attributes and an import {} block
    to bring it under Terraform management.

    Args:
        resource_attributes: Must contain 'allocation_id'. May contain
            'public_ip', 'domain', 'tags'.
        account_id: Target AWS account ID.
        region: AWS region.
        header: Pre-built header comment string.

    Returns:
        HclDocument with the EIP waste action configuration.
    """
    allocation_id = resource_attributes.get("allocation_id", "unknown")
    domain = resource_attributes.get("domain", "vpc")
    tags = resource_attributes.get("tags", {})

    tf_name = to_terraform_identifier(allocation_id)

    terraform_block, provider_block = _build_terraform_and_provider_blocks(region, account_id)

    # Build resource attributes
    attrs: dict = {
        "domain": domain,
    }
    if tags:
        attrs["tags"] = tags

    # aws_eip resource block
    resource_block = HclBlock(
        block_type="resource",
        labels=["aws_eip", tf_name],
        attributes=attrs,
    )

    # import {} block
    import_block = HclBlock(
        block_type="import",
        labels=[],
        attributes={
            "to": HclRawExpression(f"aws_eip.{tf_name}"),
            "id": allocation_id,
        },
    )

    return HclDocument(
        blocks=[terraform_block, provider_block, resource_block, import_block],
        header_comment=header,
    )


def _generate_load_balancer_waste(
    resource_attributes: dict, account_id: str, region: str, header: str
) -> HclDocument:
    """Generate HCL for deleting a load balancer via import-then-destroy.

    Supports ALB/NLB (aws_lb) and Classic (aws_elb) load balancers.

    Args:
        resource_attributes: Must contain 'lb_type' ("application", "network",
            or "classic"). For ALB/NLB: 'arn', 'name', 'subnets', 'security_groups'.
            For Classic: 'name'. May contain 'tags'.
        account_id: Target AWS account ID.
        region: AWS region.
        header: Pre-built header comment string.

    Returns:
        HclDocument with the load balancer waste action configuration.
    """
    lb_type = resource_attributes.get("lb_type", "application")
    name = resource_attributes.get("name", "unknown")
    arn = resource_attributes.get("arn", "")
    subnets = resource_attributes.get("subnets", [])
    security_groups = resource_attributes.get("security_groups", [])
    tags = resource_attributes.get("tags", {})

    tf_name = to_terraform_identifier(name)

    terraform_block, provider_block = _build_terraform_and_provider_blocks(region, account_id)

    if lb_type == "classic":
        # Classic Load Balancer uses aws_elb
        attrs: dict = {
            "name": name,
        }
        if tags:
            attrs["tags"] = tags

        resource_block = HclBlock(
            block_type="resource",
            labels=["aws_elb", tf_name],
            attributes=attrs,
        )

        # For Classic ELB, import ID is the name
        import_id = name
        import_to = f"aws_elb.{tf_name}"
    else:
        # ALB or NLB uses aws_lb
        attrs = {
            "name": name,
            "load_balancer_type": lb_type,
        }
        if subnets:
            attrs["subnets"] = subnets
        if security_groups:
            attrs["security_groups"] = security_groups
        if tags:
            attrs["tags"] = tags

        resource_block = HclBlock(
            block_type="resource",
            labels=["aws_lb", tf_name],
            attributes=attrs,
        )

        # For ALB/NLB, import ID is the ARN
        import_id = arn if arn else name
        import_to = f"aws_lb.{tf_name}"

    # import {} block
    import_block = HclBlock(
        block_type="import",
        labels=[],
        attributes={
            "to": HclRawExpression(import_to),
            "id": import_id,
        },
    )

    return HclDocument(
        blocks=[terraform_block, provider_block, resource_block, import_block],
        header_comment=header,
    )
